# Cloud Build Configuration which:
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: terraform-google-initialize
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # create this resource if TPU, MIG or _SHARED_PD is not specified
    if [[ ${_BUILD_ACTION} == "initialize" && ${_TPU} == "default" && ${_MIG} == "default" && ${_SHARED_PD} == "default" ]] 
    then
      gcloud builds submit --config=./env_setup/initialize/initialize.yaml 
      wait
    # skip in all other conditions
    fi

# Create GCS Buckets
- name: 'gcr.io/cloud-builders/gcloud'
  id: terraform-google-gcs
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # destroy this resource if TPU, MIG or _SHARED_PD is not specified
    if [[ ${_BUILD_ACTION} == "destroy" && ${_TPU} == "default" && ${_MIG} == "default" && ${_SHARED_PD} == "default" ]] 
    then
      gcloud builds submit --config=./env_setup/terraform-google-gcs/terraform-google-gcs.yaml --substitutions _BUILD_ACTION=destroy
      wait 
    # skip in all other conditions
    fi 

# CREATE filestore
- name: 'gcr.io/cloud-builders/gcloud'
  id: terraform-google-filestore
  waitFor:
  - terraform-google-gcs
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # create this resource if TPU, MIG or _SHARED_PD is not specified
    if [[ ${_BUILD_ACTION} == "create" && ${_TPU} == "default" && ${_MIG} == "default" && ${_SHARED_PD} == "default" ]] 
    then
      gcloud builds submit --config=./env_setup/terraform-google-filestore/terraform-google-filestore.yaml --substitutions _BUILD_ACTION=create
      wait
    # destroy this resource if TPU, MIG or _SHARED_PD is not specified
    elif [[ ${_BUILD_ACTION} == "destroy" && ${_TPU} == "default" && ${_MIG} == "default" && ${_SHARED_PD} == "default" ]]
    then
      gcloud builds submit --config=./env_setup/terraform-google-filestore/terraform-google-filestore.yaml --substitutions _BUILD_ACTION=destroy
      wait 
    # skip in all other conditions
    fi 

# Create CLOUD TPU 
- name: 'gcr.io/cloud-builders/gcloud'
  id: terraform-google-tpu
  waitFor:
    - terraform-google-gcs
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # create this resource if TPU is specified
    if [[ ${_BUILD_ACTION} == "update"  &&  ${_TPU} == "true" ]] || [[ ${_BUILD_ACTION} == "create" && ${_TPU} == "default" && ${_MIG} == "default" && ${_SHARED_PD} == "default" ]]
    then
      gcloud builds submit --config=./env_setup/terraform-google-tpu/terraform-google-tpu.yaml --substitutions _BUILD_ACTION=create
      wait
    # destroy this resource if TPU specified
    elif [[ ${_BUILD_ACTION} == "destroy"  &&  ${_TPU} == "true" ]] || [[ ${_BUILD_ACTION} == "destroy" && ${_TPU} == "default" && ${_MIG} == "default" && ${_SHARED_PD} == "default" ]]
    then
      gcloud builds submit --config=./env_setup/terraform-google-tpu/terraform-google-tpu.yaml --substitutions _BUILD_ACTION=destroy
      wait 
    # skip in all other conditions
    fi 

# Create SHARED_PD 
- name: 'gcr.io/cloud-builders/gcloud'
  id: terraform-google-disk
  waitFor:
    - terraform-google-gcs
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # create this resource if SHARED_PD is specified
    if [[ ${_BUILD_ACTION} == "update"  &&  ${_SHARED_PD} == "true" ]] || [[ ${_BUILD_ACTION} == "create" && ${_TPU} == "default" && ${_MIG} == "default" && ${_SHARED_PD} == "default" ]]
    then
      gcloud builds submit --config=./env_setup/terraform-google-disk/terraform-google-disk-create.yaml 
      wait
    # destroy this resource if SHARED_PD specified
    elif [[ ${_BUILD_ACTION} == "destroy"  &&  ${_SHARED_PD} == "true" ]] || [[ ${_BUILD_ACTION} == "destroy" && ${_TPU} == "default" && ${_MIG} == "default" && ${_SHARED_PD} == "default" ]]
    then
      gcloud builds submit --config=./env_setup/terraform-google-disk/terraform-google-disk-destroy.yaml
      wait 
    # skip in all other conditions
    fi 

substitutions:
    _BUILD_ACTION: default
    _TPU: default
    _MIG: default
    _SHARED_PD: default
timeout: 4000s


# TODO: Ability to set TPU Runtime when specified 

# TODO: Cloud build to refresh instances based on changes to github

# TODO: CLoud build TF to turn off enviroment and save data to GCS bucket, 

# TODO: add ability to trigger changes, watching the github checkin 



